In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

In [4]:
# 1. Create DataFrame
df = pd.DataFrame([85,78,36], columns=['Col_Name'])
print(df)

   Col_Name
0        85
1        78
2        36

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data = {
    'Name':['Atul','Ankit','abhinav'],
    'Age':[18,15,17],
    'salary':[60000,70000,80000]
}

In [7]:
df = pd.DataFrame(data)
print(df)

      Name  Age  salary
0     Atul   18   60000
1    Ankit   15   70000
2  abhinav   17   80000

In [8]:
# 2. Basic DataFrame Understanding

In [9]:
df.head()  # top rows

      Name  Age  salary
0     Atul   18   60000
1    Ankit   15   70000
2  abhinav   17   80000

In [10]:
df.tail(2)  # bottom rows

      Name  Age  salary
1    Ankit   15   70000
2  abhinav   17   80000

In [11]:
df.shape  # (row, column)

(3, 3)

In [12]:
df.columns # show columns

Index(['Name', 'Age', 'salary'], dtype='object')

In [13]:
df.rename(columns={'salary':'M_salary'})

      Name  Age  M_salary
0     Atul   18     60000
1    Ankit   15     70000
2  abhinav   17     80000

In [14]:
df

      Name  Age  salary
0     Atul   18   60000
1    Ankit   15   70000
2  abhinav   17   80000

In [15]:
df.rename(columns={'salary':'M_salary'}, inplace=True)

In [16]:
df

      Name  Age  M_salary
0     Atul   18     60000
1    Ankit   15     70000
2  abhinav   17     80000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      3 non-null      object
 1   Age       3 non-null      int64
 2   M_salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [18]:
df.describe()   # Show statistical summary

             Age  M_salary
count   3.000000       3.0
mean   16.666667   70000.0
std     1.527525   10000.0
min    15.000000   60000.0
25%    16.000000   65000.0
50%    17.000000   70000.0
75%    17.500000   75000.0
max    18.000000   80000.0

# 3. Save and Load Data from CSV

In [19]:
# Save
df.to_csv('Test_data.csv', index=False)  # Save on same folder where your current file work

In [34]:
Load_df = pd.read_csv('Test_data.csv')   # import Dataframe
Load_df

      Name  Age  M_salary
0     Atul   18     60000
1    Ankit   15     70000
2  abhinav   17     80000
3   Aditya   20     65000
4    Kunal   21     75000

# 4. Rows & Columns - Selection

In [35]:
# Select Column
Load_df[['Name']] # For Single Column
Load_df[['Name','M_salary']] # For N Columns

      Name  M_salary
0     Atul     60000
1    Ankit     70000
2  abhinav     80000
3   Aditya     65000
4    Kunal     75000

In [36]:
# Select Rows
# loc - Label based index
Load_df.loc[Load_df.Name=='Atul']

   Name  Age  M_salary
0  Atul   18     60000

In [37]:
Load_df.loc[(Load_df.Name=='Aditya')&(Load_df.M_salary>=50000)]

     Name  Age  M_salary
3  Aditya   20     65000

In [40]:
Load_df.loc[0:2] # include 0-2 all value

      Name  Age  M_salary
0     Atul   18     60000
1    Ankit   15     70000
2  abhinav   17     80000

In [31]:
# iloc - index-value based
Load_df.iloc[2]

Name        abhinav
Age              17
M_salary      80000
Name: 2, dtype: object

In [42]:
# Multiple rows
Load_df.iloc[0:2]    # [start:stop:step] include value accept 2

    Name  Age  M_salary
0   Atul   18     60000
1  Ankit   15     70000

# 5. Filter DataFrame

In [47]:
Age_filter = Load_df[Load_df['Age'] > 17]

In [48]:
Age_filter

     Name  Age  M_salary
0    Atul   18     60000
3  Aditya   20     65000
4   Kunal   21     75000

In [50]:
Load_df[(Load_df['Age'] >= 18) & (Load_df['M_salary'] > 60000)]

     Name  Age  M_salary
3  Aditya   20     65000
4   Kunal   21     75000